from fastapi import APIRouter, Depends, UploadFile, File, Form, HTTPException
from typing import Optional
from app.api.v1.endpoints import auth
from app.services.storage import storage
from app.services.database import db
from app.services.blockchain import blockchain
from app.services.ai import ai_service
import uuid
from datetime import datetime

router = APIRouter()

@router.get("/{case_id}")
def get_case_evidence(case_id: str):
    """
    Get all evidence metadata for a specific case.
    This includes the file hash generated by the Lambda function.
    """
    return db.list_case_evidence(case_id)

@router.post("/upload")
async def upload_evidence(
    file: UploadFile = File(...),
    case_id: str = Form(...),
    current_user: auth.User = Depends(auth.get_current_polaris_user)
):
    # 1. Read file content
    content = await file.read()
    
    # 2. Compute Hash
    file_hash = blockchain.calculate_hash(content)
    
    # 3. Upload to Storage
    # Reset cursor for upload
    file.file.seek(0)
    file_url = storage.upload_file(file.file, f"{case_id}/{file.filename}", file.content_type or "application/octet-stream")
    
    # 4. Anchor to Blockchain
    evidence_id = str(uuid.uuid4())
    tx_hash = blockchain.store_hash_on_chain(case_id, evidence_id, file_hash)
    
    # 5. Store Metadata
    metadata = {
        "id": evidence_id,
        "case_id": case_id,
        "filename": file.filename,
        "uploader": current_user.username,
        "tx_hash": tx_hash,
        "url": file_url,
        "uploaded_at": str(datetime.now())
    }
    db.store_evidence_metadata(metadata)
    
    # 6. Trigger AI (Async in real world, sync here for MVP)
    # We might extract text if it's a doc, here we just pass filename as dummy content
    ai_summary = ai_service.generate_summary(f"Evidence file: {file.filename}")
    
    return {
        "evidence_id": evidence_id,
        "hash": file_hash,
        "tx_hash": tx_hash,
        "ai_summary": ai_summary
    }

@router.get("/{evidence_id}/verify")
async def verify_evidence(
    evidence_id: str,
    current_user: auth.User = Depends(auth.get_current_user) # Forensics or Judge
):
    # Check permissions
    if current_user.role not in ["Forensics", "Judge"]:
         raise HTTPException(status_code=403, detail="Unauthorized")

    # 1. Get Metadata
    metadata = db.get_evidence_metadata(evidence_id)
    if not metadata:
        raise HTTPException(status_code=404, detail="Evidence not found")
        
    # 2. Get Transaction Hash
    tx_hash = metadata.get('tx_hash')
    
    # 3. Verify against Blockchain
    # In a full implementation, we must download the file from S3 (metadata['url']) 
    # and re-calculate its hash to compare with the blockchain.
    # For this MVP, we show the stored blockchain transaction hash.
    
    stored_hash_on_chain = blockchain._get_hash_from_ledger(evidence_id)
    
    return {
        "evidence_id": evidence_id,
        "status": "SECURED_ON_CHAIN" if stored_hash_on_chain else "NOT_FOUND",
        "tx_hash": tx_hash,
        "blockchain_record": stored_hash_on_chain
    }
