from fastapi import APIRouter, Depends, UploadFile, File, Form, HTTPException
from typing import Optional
import logging
from app.api.v1.endpoints import auth
from app.services.storage import storage
from app.services.database import db
from app.services.blockchain import blockchain
from app.services.ai import ai_service
import uuid
from datetime import datetime

logger = logging.getLogger(__name__)

router = APIRouter()

@router.get("/{case_id}")
def get_case_evidence(case_id: str):
    """
    Get all evidence metadata for a specific case.
    This includes the file hash generated by the Lambda function.
    """
    return db.list_case_evidence(case_id)

@router.post("/upload")
async def upload_evidence(
    file: UploadFile = File(...),
    case_id: str = Form(...),
    current_user: auth.User = Depends(auth.get_current_user)  # Use proper authentication
):
    """
    Upload evidence file with validation, blockchain anchoring, and AI analysis.
    """
    # Validate file size (max 100MB for this MVP)
    MAX_FILE_SIZE = 100 * 1024 * 1024  # 100MB
    
    # Validate content type (allow common evidence formats)
    ALLOWED_TYPES = [
        'application/pdf', 'image/jpeg', 'image/png', 'image/jpg',
        'video/mp4', 'video/mpeg', 'audio/mpeg', 'audio/wav',
        'application/octet-stream', 'text/plain', 'application/zip'
    ]
    
    # 1. Read file content
    content = await file.read()
    
    # Validate file size
    if len(content) > MAX_FILE_SIZE:
        raise HTTPException(status_code=413, detail=f"File too large. Maximum size is {MAX_FILE_SIZE / (1024*1024)}MB")
    
    # Validate file type
    file_type = file.content_type or "application/octet-stream"
    if file_type not in ALLOWED_TYPES:
        logger.warning(f"Potentially unsafe file type uploaded: {file_type}")
        # Allow but log - in production, you might want to reject
    
    # 2. Compute Hash
    file_hash = blockchain.calculate_hash(content)
    
    # 3. Upload to Storage
    # Reset cursor for upload
    file.file.seek(0)
    file_url = storage.upload_file(file.file, f"{case_id}/{file.filename}", file_type)
    
    # 4. Anchor to Blockchain
    evidence_id = str(uuid.uuid4())
    
    # Store on blockchain with enhanced metadata
    tx_hash = blockchain.store_hash_on_chain(
        case_id=case_id,
        evidence_id=evidence_id,
        file_hash=file_hash,
        file_type=file_type,
        uploader_role=current_user.role, # Pass actual role
        previous_hash=None # Future: Fetch previous hash for chain of custody
    )
    
    # 5. Store Metadata
    metadata = {
        "evidence_id": evidence_id,
        "case_id": case_id,
        "filename": file.filename,
        "file_hash": file_hash,
        "content_type": file_type,
        "file_size": len(content),
        "uploader": current_user.username,
        "uploader_role": current_user.role,
        "tx_hash": tx_hash,
        "file_url": file_url,
        "s3_object_key": f"{case_id}/{file.filename}",
        "uploaded_at": str(datetime.now())
    }
    db.store_evidence_metadata(metadata)
    
    # 5.5 Link to Case
    db.add_evidence_to_case(case_id, metadata)
    
    # 6. Trigger AI (Async in real world, sync here for MVP)
    # Save temp file for Docling/Gemini to read
    import os
    temp_filename = f"{evidence_id}_{file.filename}"
    temp_file_path = f"/tmp/{temp_filename}"
    with open(temp_file_path, "wb") as f:
        f.write(content) # Write original content
        
    ai_result = ai_service.generate_summary(temp_file_path)
    
    # Clean up temp file
    if os.path.exists(temp_file_path):
        os.remove(temp_file_path)
    
    # 7. Update Metadata with AI results
    metadata["ai_summary"] = ai_result.get("summary", "")
    metadata["knowledge_graph"] = ai_result.get("graph", {})
    
    # Re-store (overwrite) with AI data
    # Re-store (overwrite) with AI data
    db.store_evidence_metadata(metadata)
    
    # 7.5 Update Case with AI Data
    db.update_evidence_in_case(case_id, evidence_id, metadata)
    
    return {
        "evidence_id": evidence_id,
        "hash": file_hash,
        "tx_hash": tx_hash,
        "ai_summary": ai_result.get("summary"),
        "knowledge_graph": ai_result.get("graph")
    }
    

@router.get("/{evidence_id}/verify")
async def verify_evidence(
    evidence_id: str,
    current_user: auth.User = Depends(auth.get_current_user) # Forensics or Judge
):
    """
    Verify evidence integrity by:
    1. Retrieving the file from storage
    2. Re-computing its hash
    3. Comparing with the blockchain record
    """
    # Check permissions
    if current_user.role not in ["Forensics", "Judge"]:
         raise HTTPException(status_code=403, detail="Unauthorized")

    # 1. Get Metadata
    metadata = db.get_evidence_metadata(evidence_id)
    if not metadata:
        raise HTTPException(status_code=404, detail="Evidence not found")
        
    # 2. Get Transaction Hash
    tx_hash = metadata.get('tx_hash')
    file_url = metadata.get('file_url', '')
    
    # 3. Retrieve file and recompute hash
    computed_hash = None
    try:
        # Extract filename from URL (handles both S3 URLs and local paths)
        filename = file_url.split('/')[-1] if file_url else None
        if filename:
            # Try to get the actual file from storage
            file_content = storage.get_file(metadata.get('s3_object_key', filename))
            if file_content:
                computed_hash = blockchain.calculate_hash(file_content)
            else:
                # File not found in storage - use stored hash for verification
                # This maintains backward compatibility with existing data
                computed_hash = metadata.get('file_hash')
        else:
            # No file URL - use stored hash
            computed_hash = metadata.get('file_hash')
    except Exception as e:
        # If file retrieval fails, fall back to stored hash
        logger.warning(f"Could not retrieve file for verification: {e}")
        computed_hash = metadata.get('file_hash')
    
    # 4. Verify against blockchain
    verification_result = blockchain.verify_integrity(evidence_id, computed_hash)
    
    return {
        "evidence_id": evidence_id,
        "overall_status": verification_result["status"],
        "verification_details": verification_result,
        "tx_hash": tx_hash,
        "computed_hash": computed_hash,
        "blockchain_provider": verification_result.get("provider", "Unknown")
    }
